### PR TITLE
fix: polished readme

### PR DESCRIPTION
**Pull request by dr-nefardio3058**
fix in the readme, regarding code of conduct and license.

Cya! 🐱

### CODE REVIEW

**Comment by dr-nefardio3058** [comment]
@jge162 action failed

**Comment by jge162** [comment]
> @jge162 action failed
> 
> image

I see the issue now. The action.yml I made uses repo-token instead of GitHub-token. So it’s not a valid input. I’ll fix it later. Thanks.

**Review by jge162 — APPROVED** [review]

**Comment by dr-nefardio3058** [comment]
> 
> I see the issue now. The action.yml I made uses repo-token instead of GitHub-token. So it’s not a valid input. I’ll fix it later. Thanks.

Lemme know when fixed so i submit a PR

**Comment by jge162** [comment]
Will add breaks

**Pull request closed without merging**
