### PR TITLE
fix: contributing.md

### PR DESCRIPTION
**Pull request by dr-nefardio3058**
Corrected some typos in security.md

### CODE REVIEW

**Comment by dr-nefardio3058** [comment]
@jge162 fail

**Comment by jge162** [comment]
> Contributor

Correct, trying to fix action.yml now. I will let you know once its done. thanks

**Comment by dr-nefardio3058** [comment]
why you closed this PR?

**Comment by jge162** [comment]
> why you closed this PR?

Sorry thought it was a test PR, did not realize you made changes until you put note.

**Comment by dr-nefardio3058** [comment]
> > why you closed this PR?
> 
> Sorry thought it was a test PR, did not realize you made changes until you put note.

i made changes in the other 2 too

**Comment by jge162** [comment]
> > > why you closed this PR?
> > 
> > 
> > Sorry thought it was a test PR, did not realize you made changes until you put note.
> 
> i made changes in the other 2 too

I made the changes manually. I added the  <br> <br> to readme etc...

**Pull request merged**
