### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Geo4u**
## Please provide good notes, to help us understand request: 
- [ ] Remember to include a summary of the changes you made!
- [ ] Which issues have been fixed!
- [ ] Pull request comments below here please. Thank you.

### CODE REVIEW

**Review by jge162 — APPROVED** [review]

**Comment by dr-nefardio3058** [comment]
Empty PR? Hello?

**Comment by dr-nefardio3058** [comment]
> She was testing something I asked for help with. To auto approve pull request for you and her.

Remember that this PR branch "Geo4u-patch-1" stills active.

**Comment by jge162** [comment]
I’m going to add an action to also allow auto merges on both your pull requests later today. But, busy at the moment.

**Comment by jge162** [comment]
Condition for auto merge will just be, approval from me. Which we just finished.

**Pull request merged**
